<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>=1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
        <?php foreach ($block->getStores() as $_lang): ?>
            
         <?php //if ($_lang->getId() != $block->getCurrentStoreId()): ?>
        <a href="#" class="language-selector" data-post='<?php echo $block->getTargetStorePostData($_lang); ?>'>
                        <?php echo $block->escapeHtml($_lang->getName()) ?></a>
            <?php //endif; ?>
        <?php endforeach; ?>
<?php endif; ?>

